### ISSUE TITLE
fix contact IBLI button in "What is IBLI" page

### ISSUE THREAD

**Issue by niryariv** [Gizra/IBLI#156]
In http://dev-ibli.gotpantheon.com/content/what-ibli link the bottom right "contact IBLI" button to http://dev-ibli.gotpantheon.com/contact-us

**Comment by Moo64c** [comment]
@niryariv This is content, so it can be edited later when the site goes live (and changed in the migration file - `ibli_migrate/html/what-is-ibli.html`.

Leaving this open for now.

**Comment by Moo64c** [comment]
@niryariv Fixed by Brice
Was a menu system problem
![selection_004](https://cloud.githubusercontent.com/assets/2690042/3812998/7ca8b2e4-1caf-11e4-9db9-2ba01dbd7c1c.png)

**Comment by niryariv** [comment]
still seeing the old page with no form on dev.. 

![screen shot 2014-08-05 at 5 57 12 pm](https://cloud.githubusercontent.com/assets/1771/3813164/df3042c8-1cb0-11e4-8983-6cfae145c6ab.png)

**Comment by Moo64c** [comment]
Fixed again, a permission issue (was logged in as admin)
BTW Brice confirmed drush is problematic with the site.
http://dev-ibli.gotpantheon.com/contact-us

**Comment by niryariv** [comment]
fixed now, closing.
